{% set name = "mps-motion" %}
{% set name_underscore = "mps_motion" %}
{% set version = "0.4.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name_underscore }}-{{ version }}.tar.gz"
  sha256: f27f29649a5735764513b220cbbaacd91319a0831d3b508ce022a7fdaf1b58de

build:
  number: 0
  noarch: python
  entry_points:
    - "mps-motion=mps_motion.__main__:app"
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ap_features
    - cardiac-mps
    - daiquiri
    - dask-image
    - dask
    - h5py
    - matplotlib-base
    - numba
    - numpy
    - libopencv
    - opencv
    - py-opencv
    - scipy
    - tqdm
    - typer
    - typing_extensions
test:
  requires:
    - python {{ python_min }}
  imports:
    - mps_motion

  commands:
    - mps-motion --help

about:
  home: https://github.com/ComputationalPhysiology/mps_motion
  summary: Library for tracking motion in cardiac mps data
  license: MIT
  license_file: LICENSE
  doc_url: https://computationalphysiology.github.io/mps_motion/
  dev_url: https://github.com/ComputationalPhysiology/mps_motion

extra:
  recipe-maintainers:
    - finsberg
