{% set name = "mps-motion" %}
{% set name_underscore = "mps_motion" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name_underscore }}-{{ version }}.tar.gz"
  sha256: fcf1d73963b4e7427a70eeaed3d62d5e400eeaeea5fa12d8d2c182baa70f2b1f

build:
  number: 0
  noarch: python
  entry_points:
    - "mps-motion=mps_motion.__main__:app"
  script: python -m pip install -v --no-deps .

requirements:
  build:
    - python
    - setuptools
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ap_features
    - cardiac-mps
    - daiquiri
    - dask-image
    - dask
    - h5py
    - matplotlib-base
    - numba
    - numpy
    - libopencv
    - opencv
    - py-opencv
    - scipy
    - tqdm
    - typer
    - typing_extensions
test:
  imports:
    - mps_motion

  commands:
    - mps-motion --help

about:
  home: https://github.com/ComputationalPhysiology/mps_motion
  summary: Library for tracking motion in cardiac mps data
  license: MIT
  license_file: LICENSE
  doc_url: https://computationalphysiology.github.io/mps_motion/
  dev_url: https://github.com/ComputationalPhysiology/mps_motion

extra:
  recipe-maintainers:
    - finsberg
